export { default as Home} from './Home'
export { default as Navigation} from './Navigation'
export { default as Mainmenu} from './Mainmenu'
export { default as Menutrigger} from './Menutrigger'
export { default as Slider} from './Slider'
export { default as Homecarousel} from './Homecarousel'